source "https://rubygems.org"
gem "jekyll-theme-chirpy"
gem "jekyll", "~> 4.3"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"
gem "rouge"
